name: useless_kit
description: Useless kit means they are always useless.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cryptography: ^2.0.5
  get_it: ^7.2.0
  go_router: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pointycastle: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  go_router_builder: ^1.0.7
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
